# create this in .github/workflows/ci.yml
name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    services:
      db:
        image: postgres:14
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ["25.0.4"]
        elixir: ["1.14.0-rc.1"]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix format --check-formatted
      - run: mix deps.get
      - run: mix test
